
package com.totalplay.soa.salesforce.createcommentinsf.bpelprocesscreatecommentinsf;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "bpelprocesscreatecommentinsf_client_ep", targetNamespace = "http://soa.totalplay.com/SalesForce/CreateCommentInSF/BPELProcessCreateCommentInSF", wsdlLocation = "http://10.216.8.198/soa-infra/services/SalesForce/CreateCommentInSF/bpelprocesscreatecommentinsf_client_ep?wsdl")
public class BpelprocesscreatecommentinsfClientEp
    extends Service
{

    private final static URL BPELPROCESSCREATECOMMENTINSFCLIENTEP_WSDL_LOCATION;
    private final static WebServiceException BPELPROCESSCREATECOMMENTINSFCLIENTEP_EXCEPTION;
    private final static QName BPELPROCESSCREATECOMMENTINSFCLIENTEP_QNAME = new QName("http://soa.totalplay.com/SalesForce/CreateCommentInSF/BPELProcessCreateCommentInSF", "bpelprocesscreatecommentinsf_client_ep");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.216.8.198/soa-infra/services/SalesForce/CreateCommentInSF/bpelprocesscreatecommentinsf_client_ep?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BPELPROCESSCREATECOMMENTINSFCLIENTEP_WSDL_LOCATION = url;
        BPELPROCESSCREATECOMMENTINSFCLIENTEP_EXCEPTION = e;
    }

    public BpelprocesscreatecommentinsfClientEp() {
        super(__getWsdlLocation(), BPELPROCESSCREATECOMMENTINSFCLIENTEP_QNAME);
    }

    public BpelprocesscreatecommentinsfClientEp(WebServiceFeature... features) {
        super(__getWsdlLocation(), BPELPROCESSCREATECOMMENTINSFCLIENTEP_QNAME, features);
    }

    public BpelprocesscreatecommentinsfClientEp(URL wsdlLocation) {
        super(wsdlLocation, BPELPROCESSCREATECOMMENTINSFCLIENTEP_QNAME);
    }

    public BpelprocesscreatecommentinsfClientEp(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BPELPROCESSCREATECOMMENTINSFCLIENTEP_QNAME, features);
    }

    public BpelprocesscreatecommentinsfClientEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BpelprocesscreatecommentinsfClientEp(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BPELProcessCreateCommentInSF
     */
    @WebEndpoint(name = "BPELProcessCreateCommentInSF_pt")
    public BPELProcessCreateCommentInSF getBPELProcessCreateCommentInSFPt() {
        return super.getPort(new QName("http://soa.totalplay.com/SalesForce/CreateCommentInSF/BPELProcessCreateCommentInSF", "BPELProcessCreateCommentInSF_pt"), BPELProcessCreateCommentInSF.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BPELProcessCreateCommentInSF
     */
    @WebEndpoint(name = "BPELProcessCreateCommentInSF_pt")
    public BPELProcessCreateCommentInSF getBPELProcessCreateCommentInSFPt(WebServiceFeature... features) {
        return super.getPort(new QName("http://soa.totalplay.com/SalesForce/CreateCommentInSF/BPELProcessCreateCommentInSF", "BPELProcessCreateCommentInSF_pt"), BPELProcessCreateCommentInSF.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BPELPROCESSCREATECOMMENTINSFCLIENTEP_EXCEPTION!= null) {
            throw BPELPROCESSCREATECOMMENTINSFCLIENTEP_EXCEPTION;
        }
        return BPELPROCESSCREATECOMMENTINSFCLIENTEP_WSDL_LOCATION;
    }

}
