
package com.totalplay.soa.salesforce.createticketinsf.bpelcreateticketinsf;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BPELCreateTicketInSF", targetNamespace = "http://soa.totalplay.com/SalesForce/CreateTicketInSF/BPELCreateTicketInSF")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BPELCreateTicketInSF {


    /**
     * 
     * @param descripcion
     * @param grupoCodificador
     * @param idResult
     * @param resumen
     * @param numeroDeSerie
     * @param login
     * @param codificacion
     * @param prioridad
     * @param numeroTicket
     * @param idTicket
     * @param result
     * @param estatus
     * @param fechaApertura
     * @param contact
     * @param resultDescription
     */
    @WebMethod(action = "process")
    @RequestWrapper(localName = "process", targetNamespace = "http://soa.totalplay.com/SalesForce/CreateTicketInSF/BPELCreateTicketInSF", className = "com.totalplay.soa.salesforce.createticketinsf.bpelcreateticketinsf.Process")
    @ResponseWrapper(localName = "processResponse", targetNamespace = "http://soa.totalplay.com/SalesForce/CreateTicketInSF/BPELCreateTicketInSF", className = "com.totalplay.soa.salesforce.createticketinsf.bpelcreateticketinsf.ProcessResponse")
    public void process(
        @WebParam(name = "Login", targetNamespace = "http://soa.totalplay.com/SalesForce/CreateTicketInSF/BPELCreateTicketInSF")
        com.totalplay.soa.salesforce.createticketinsf.bpelcreateticketinsf.Process.Login login,
        @WebParam(name = "IdTicket", targetNamespace = "http://soa.totalplay.com/SalesForce/CreateTicketInSF/BPELCreateTicketInSF")
        String idTicket,
        @WebParam(name = "Resumen", targetNamespace = "http://soa.totalplay.com/SalesForce/CreateTicketInSF/BPELCreateTicketInSF")
        String resumen,
        @WebParam(name = "Descripcion", targetNamespace = "http://soa.totalplay.com/SalesForce/CreateTicketInSF/BPELCreateTicketInSF")
        String descripcion,
        @WebParam(name = "GrupoCodificador", targetNamespace = "http://soa.totalplay.com/SalesForce/CreateTicketInSF/BPELCreateTicketInSF")
        String grupoCodificador,
        @WebParam(name = "Codificacion", targetNamespace = "http://soa.totalplay.com/SalesForce/CreateTicketInSF/BPELCreateTicketInSF")
        String codificacion,
        @WebParam(name = "Estatus", targetNamespace = "http://soa.totalplay.com/SalesForce/CreateTicketInSF/BPELCreateTicketInSF")
        String estatus,
        @WebParam(name = "FechaApertura", targetNamespace = "http://soa.totalplay.com/SalesForce/CreateTicketInSF/BPELCreateTicketInSF")
        String fechaApertura,
        @WebParam(name = "Prioridad", targetNamespace = "http://soa.totalplay.com/SalesForce/CreateTicketInSF/BPELCreateTicketInSF")
        String prioridad,
        @WebParam(name = "NumeroDeSerie", targetNamespace = "http://soa.totalplay.com/SalesForce/CreateTicketInSF/BPELCreateTicketInSF")
        String numeroDeSerie,
        @WebParam(name = "Contact", targetNamespace = "http://soa.totalplay.com/SalesForce/CreateTicketInSF/BPELCreateTicketInSF")
        List<com.totalplay.soa.salesforce.createticketinsf.bpelcreateticketinsf.Process.Contact> contact,
        @WebParam(name = "IdResult", targetNamespace = "http://soa.totalplay.com/SalesForce/CreateTicketInSF/BPELCreateTicketInSF", mode = WebParam.Mode.OUT)
        Holder<String> idResult,
        @WebParam(name = "Result", targetNamespace = "http://soa.totalplay.com/SalesForce/CreateTicketInSF/BPELCreateTicketInSF", mode = WebParam.Mode.OUT)
        Holder<String> result,
        @WebParam(name = "ResultDescription", targetNamespace = "http://soa.totalplay.com/SalesForce/CreateTicketInSF/BPELCreateTicketInSF", mode = WebParam.Mode.OUT)
        Holder<String> resultDescription,
        @WebParam(name = "numeroTicket", targetNamespace = "http://soa.totalplay.com/SalesForce/CreateTicketInSF/BPELCreateTicketInSF", mode = WebParam.Mode.OUT)
        Holder<String> numeroTicket);

}
