
package com.totalplay.soa.salesforce.createticketinsf.bpelcreateticketinsf;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "bpelcreateticketinsf_client_ep", targetNamespace = "http://soa.totalplay.com/SalesForce/CreateTicketInSF/BPELCreateTicketInSF", wsdlLocation = "http://10.216.8.198:80/soa-infra/services/SalesForce/CreateTicketInSF/bpelcreateticketinsf_client_ep?wsdl")
public class BpelcreateticketinsfClientEp
    extends Service
{

    private final static URL BPELCREATETICKETINSFCLIENTEP_WSDL_LOCATION;
    private final static WebServiceException BPELCREATETICKETINSFCLIENTEP_EXCEPTION;
    private final static QName BPELCREATETICKETINSFCLIENTEP_QNAME = new QName("http://soa.totalplay.com/SalesForce/CreateTicketInSF/BPELCreateTicketInSF", "bpelcreateticketinsf_client_ep");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.216.8.198:80/soa-infra/services/SalesForce/CreateTicketInSF/bpelcreateticketinsf_client_ep?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BPELCREATETICKETINSFCLIENTEP_WSDL_LOCATION = url;
        BPELCREATETICKETINSFCLIENTEP_EXCEPTION = e;
    }

    public BpelcreateticketinsfClientEp() {
        super(__getWsdlLocation(), BPELCREATETICKETINSFCLIENTEP_QNAME);
    }

    public BpelcreateticketinsfClientEp(WebServiceFeature... features) {
        super(__getWsdlLocation(), BPELCREATETICKETINSFCLIENTEP_QNAME, features);
    }

    public BpelcreateticketinsfClientEp(URL wsdlLocation) {
        super(wsdlLocation, BPELCREATETICKETINSFCLIENTEP_QNAME);
    }

    public BpelcreateticketinsfClientEp(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BPELCREATETICKETINSFCLIENTEP_QNAME, features);
    }

    public BpelcreateticketinsfClientEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BpelcreateticketinsfClientEp(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BPELCreateTicketInSF
     */
    @WebEndpoint(name = "BPELCreateTicketInSF_pt")
    public BPELCreateTicketInSF getBPELCreateTicketInSFPt() {
        return super.getPort(new QName("http://soa.totalplay.com/SalesForce/CreateTicketInSF/BPELCreateTicketInSF", "BPELCreateTicketInSF_pt"), BPELCreateTicketInSF.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BPELCreateTicketInSF
     */
    @WebEndpoint(name = "BPELCreateTicketInSF_pt")
    public BPELCreateTicketInSF getBPELCreateTicketInSFPt(WebServiceFeature... features) {
        return super.getPort(new QName("http://soa.totalplay.com/SalesForce/CreateTicketInSF/BPELCreateTicketInSF", "BPELCreateTicketInSF_pt"), BPELCreateTicketInSF.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BPELCREATETICKETINSFCLIENTEP_EXCEPTION!= null) {
            throw BPELCREATETICKETINSFCLIENTEP_EXCEPTION;
        }
        return BPELCREATETICKETINSFCLIENTEP_WSDL_LOCATION;
    }

}
