
package com.totalplay.soa.salesforce.changestatusticketsf.bpelprocesschangestatusticketsf;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "bpelprocesschangestatusticketsf_client_ep", targetNamespace = "http://soa.totalplay.com/SalesForce/ChangeStatusTicketSF/BPELProcessChangeStatusTicketSF", wsdlLocation = "http://10.216.8.198/soa-infra/services/SalesForce/ChangeStatusTicketSF/bpelprocesschangestatusticketsf_client_ep?WSDL")
public class BpelprocesschangestatusticketsfClientEp
    extends Service
{

    private final static URL BPELPROCESSCHANGESTATUSTICKETSFCLIENTEP_WSDL_LOCATION;
    private final static WebServiceException BPELPROCESSCHANGESTATUSTICKETSFCLIENTEP_EXCEPTION;
    private final static QName BPELPROCESSCHANGESTATUSTICKETSFCLIENTEP_QNAME = new QName("http://soa.totalplay.com/SalesForce/ChangeStatusTicketSF/BPELProcessChangeStatusTicketSF", "bpelprocesschangestatusticketsf_client_ep");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.216.8.198/soa-infra/services/SalesForce/ChangeStatusTicketSF/bpelprocesschangestatusticketsf_client_ep?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BPELPROCESSCHANGESTATUSTICKETSFCLIENTEP_WSDL_LOCATION = url;
        BPELPROCESSCHANGESTATUSTICKETSFCLIENTEP_EXCEPTION = e;
    }

    public BpelprocesschangestatusticketsfClientEp() {
        super(__getWsdlLocation(), BPELPROCESSCHANGESTATUSTICKETSFCLIENTEP_QNAME);
    }

    public BpelprocesschangestatusticketsfClientEp(WebServiceFeature... features) {
        super(__getWsdlLocation(), BPELPROCESSCHANGESTATUSTICKETSFCLIENTEP_QNAME, features);
    }

    public BpelprocesschangestatusticketsfClientEp(URL wsdlLocation) {
        super(wsdlLocation, BPELPROCESSCHANGESTATUSTICKETSFCLIENTEP_QNAME);
    }

    public BpelprocesschangestatusticketsfClientEp(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BPELPROCESSCHANGESTATUSTICKETSFCLIENTEP_QNAME, features);
    }

    public BpelprocesschangestatusticketsfClientEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BpelprocesschangestatusticketsfClientEp(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BPELProcessChangeStatusTicketSF
     */
    @WebEndpoint(name = "BPELProcessChangeStatusTicketSF_pt")
    public BPELProcessChangeStatusTicketSF getBPELProcessChangeStatusTicketSFPt() {
        return super.getPort(new QName("http://soa.totalplay.com/SalesForce/ChangeStatusTicketSF/BPELProcessChangeStatusTicketSF", "BPELProcessChangeStatusTicketSF_pt"), BPELProcessChangeStatusTicketSF.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BPELProcessChangeStatusTicketSF
     */
    @WebEndpoint(name = "BPELProcessChangeStatusTicketSF_pt")
    public BPELProcessChangeStatusTicketSF getBPELProcessChangeStatusTicketSFPt(WebServiceFeature... features) {
        return super.getPort(new QName("http://soa.totalplay.com/SalesForce/ChangeStatusTicketSF/BPELProcessChangeStatusTicketSF", "BPELProcessChangeStatusTicketSF_pt"), BPELProcessChangeStatusTicketSF.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BPELPROCESSCHANGESTATUSTICKETSFCLIENTEP_EXCEPTION!= null) {
            throw BPELPROCESSCHANGESTATUSTICKETSFCLIENTEP_EXCEPTION;
        }
        return BPELPROCESSCHANGESTATUSTICKETSFCLIENTEP_WSDL_LOCATION;
    }

}
