
package com.totalplay.soa.servicedesk.obtenerstatuscuentaenbrm.bpelobtenerstatuscuentaenbrm;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BPELObtenerStatusCuentaEnBrm", targetNamespace = "http://soa.totalplay.com/ServiceDesk/ObtenerStatusCuentaEnBRM/BPELObtenerStatusCuentaEnBrm")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BPELObtenerStatusCuentaEnBrm {


    /**
     * 
     * @param result
     * @param numeroSerie
     * @param idResult
     * @param statusCuenta
     * @param cuenta
     * @param resultDescription
     * @param login
     */
    @WebMethod(action = "process")
    @RequestWrapper(localName = "process", targetNamespace = "http://soa.totalplay.com/ServiceDesk/ObtenerStatusCuentaEnBRM/BPELObtenerStatusCuentaEnBrm", className = "com.totalplay.soa.servicedesk.obtenerstatuscuentaenbrm.bpelobtenerstatuscuentaenbrm.Process")
    @ResponseWrapper(localName = "processResponse", targetNamespace = "http://soa.totalplay.com/ServiceDesk/ObtenerStatusCuentaEnBRM/BPELObtenerStatusCuentaEnBrm", className = "com.totalplay.soa.servicedesk.obtenerstatuscuentaenbrm.bpelobtenerstatuscuentaenbrm.ProcessResponse")
    public void process(
        @WebParam(name = "Login", targetNamespace = "http://soa.totalplay.com/ServiceDesk/ObtenerStatusCuentaEnBRM/BPELObtenerStatusCuentaEnBrm")
        com.totalplay.soa.servicedesk.obtenerstatuscuentaenbrm.bpelobtenerstatuscuentaenbrm.Process.Login login,
        @WebParam(name = "numeroSerie", targetNamespace = "http://soa.totalplay.com/ServiceDesk/ObtenerStatusCuentaEnBRM/BPELObtenerStatusCuentaEnBrm")
        String numeroSerie,
        @WebParam(name = "IdResult", targetNamespace = "http://soa.totalplay.com/ServiceDesk/ObtenerStatusCuentaEnBRM/BPELObtenerStatusCuentaEnBrm", mode = WebParam.Mode.OUT)
        Holder<String> idResult,
        @WebParam(name = "Result", targetNamespace = "http://soa.totalplay.com/ServiceDesk/ObtenerStatusCuentaEnBRM/BPELObtenerStatusCuentaEnBrm", mode = WebParam.Mode.OUT)
        Holder<String> result,
        @WebParam(name = "ResultDescription", targetNamespace = "http://soa.totalplay.com/ServiceDesk/ObtenerStatusCuentaEnBRM/BPELObtenerStatusCuentaEnBrm", mode = WebParam.Mode.OUT)
        Holder<String> resultDescription,
        @WebParam(name = "Cuenta", targetNamespace = "http://soa.totalplay.com/ServiceDesk/ObtenerStatusCuentaEnBRM/BPELObtenerStatusCuentaEnBrm", mode = WebParam.Mode.OUT)
        Holder<String> cuenta,
        @WebParam(name = "StatusCuenta", targetNamespace = "http://soa.totalplay.com/ServiceDesk/ObtenerStatusCuentaEnBRM/BPELObtenerStatusCuentaEnBrm", mode = WebParam.Mode.OUT)
        Holder<String> statusCuenta);

}
