
package com.totalplay.soa.servicedesk.obtenerstatuscuentaenbrm.bpelobtenerstatuscuentaenbrm;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "bpelobtenerstatuscuentaenbrm_client_ep", targetNamespace = "http://soa.totalplay.com/ServiceDesk/ObtenerStatusCuentaEnBRM/BPELObtenerStatusCuentaEnBrm", wsdlLocation = "http://10.216.8.198:80/soa-infra/services/ServiceDesk/ObtenerStatusCuentaEnBRM/bpelobtenerstatuscuentaenbrm_client_ep?wsdl")
public class BpelobtenerstatuscuentaenbrmClientEp
    extends Service
{

    private final static URL BPELOBTENERSTATUSCUENTAENBRMCLIENTEP_WSDL_LOCATION;
    private final static WebServiceException BPELOBTENERSTATUSCUENTAENBRMCLIENTEP_EXCEPTION;
    private final static QName BPELOBTENERSTATUSCUENTAENBRMCLIENTEP_QNAME = new QName("http://soa.totalplay.com/ServiceDesk/ObtenerStatusCuentaEnBRM/BPELObtenerStatusCuentaEnBrm", "bpelobtenerstatuscuentaenbrm_client_ep");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.216.8.198:80/soa-infra/services/ServiceDesk/ObtenerStatusCuentaEnBRM/bpelobtenerstatuscuentaenbrm_client_ep?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BPELOBTENERSTATUSCUENTAENBRMCLIENTEP_WSDL_LOCATION = url;
        BPELOBTENERSTATUSCUENTAENBRMCLIENTEP_EXCEPTION = e;
    }

    public BpelobtenerstatuscuentaenbrmClientEp() {
        super(__getWsdlLocation(), BPELOBTENERSTATUSCUENTAENBRMCLIENTEP_QNAME);
    }

    public BpelobtenerstatuscuentaenbrmClientEp(WebServiceFeature... features) {
        super(__getWsdlLocation(), BPELOBTENERSTATUSCUENTAENBRMCLIENTEP_QNAME, features);
    }

    public BpelobtenerstatuscuentaenbrmClientEp(URL wsdlLocation) {
        super(wsdlLocation, BPELOBTENERSTATUSCUENTAENBRMCLIENTEP_QNAME);
    }

    public BpelobtenerstatuscuentaenbrmClientEp(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BPELOBTENERSTATUSCUENTAENBRMCLIENTEP_QNAME, features);
    }

    public BpelobtenerstatuscuentaenbrmClientEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BpelobtenerstatuscuentaenbrmClientEp(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BPELObtenerStatusCuentaEnBrm
     */
    @WebEndpoint(name = "BPELObtenerStatusCuentaEnBrm_pt")
    public BPELObtenerStatusCuentaEnBrm getBPELObtenerStatusCuentaEnBrmPt() {
        return super.getPort(new QName("http://soa.totalplay.com/ServiceDesk/ObtenerStatusCuentaEnBRM/BPELObtenerStatusCuentaEnBrm", "BPELObtenerStatusCuentaEnBrm_pt"), BPELObtenerStatusCuentaEnBrm.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BPELObtenerStatusCuentaEnBrm
     */
    @WebEndpoint(name = "BPELObtenerStatusCuentaEnBrm_pt")
    public BPELObtenerStatusCuentaEnBrm getBPELObtenerStatusCuentaEnBrmPt(WebServiceFeature... features) {
        return super.getPort(new QName("http://soa.totalplay.com/ServiceDesk/ObtenerStatusCuentaEnBRM/BPELObtenerStatusCuentaEnBrm", "BPELObtenerStatusCuentaEnBrm_pt"), BPELObtenerStatusCuentaEnBrm.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BPELOBTENERSTATUSCUENTAENBRMCLIENTEP_EXCEPTION!= null) {
            throw BPELOBTENERSTATUSCUENTAENBRMCLIENTEP_EXCEPTION;
        }
        return BPELOBTENERSTATUSCUENTAENBRMCLIENTEP_WSDL_LOCATION;
    }

}
